# Загрузка Pandas и очистка данных

In [5]:
import pandas as pd
import numpy as np
import plotly.express as px
from pprint import pprint
from bs4 import BeautifulSoup
from selenium import webdriver

# Расширяем диапазон отображаемых данных.
pd.set_option('display.max_rows', 50)  # показывать больше строк
pd.set_option('display.max_columns', 50)  # показывать больше колонок

In [6]:
df = pd.read_csv('main_task_new.csv')

In [28]:
# Ваш код по очистке данных и генерации новых признаков
# При необходимости добавьте ячейки
df.head()

,Restaurant_id,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
0,id_5569,Paris,"['European', 'French', 'International']",5570.0,3.5,$$ - $$$,194.0,"[['Good food at your doorstep', 'A good hotel ...",/Restaurant_Review-g187147-d1912643-Reviews-R_...,d1912643
1,id_1535,Stockholm,NaN,1537.0,4.0,NaN,10.0,"[['Unique cuisine', 'Delicious Nepalese food']...",/Restaurant_Review-g189852-d7992032-Reviews-Bu...,d7992032
2,id_352,London,"['Japanese', 'Sushi', 'Asian', 'Grill', 'Veget...",353.0,4.5,$$$$,688.0,"[['Catch up with friends', 'Not exceptional'],...",/Restaurant_Review-g186338-d8632781-Reviews-RO...,d8632781
3,id_3456,Berlin,NaN,3458.0,5.0,NaN,3.0,"[[], []]",/Restaurant_Review-g187323-d1358776-Reviews-Es...,d1358776
4,id_615,Munich,"['German', 'Central European', 'Vegetarian Fri...",621.0,4.0,$$ - $$$,84.0,"[['Best place to try a Bavarian food', 'Nice b...",/Restaurant_Review-g187309-d6864963-Reviews-Au...,d6864963

In [29]:
df.info()
type(df['Cuisine Style'].iloc[0])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Restaurant_id      40000 non-null  object
 1   City               40000 non-null  object
 2   Cuisine Style      30717 non-null  object
 3   Ranking            40000 non-null  float64
 4   Rating             40000 non-null  float64
 5   Price Range        26114 non-null  object
 6   Number of Reviews  37457 non-null  float64
 7   Reviews            40000 non-null  object
 8   URL_TA             40000 non-null  object
 9   ID_TA              40000 non-null  object
dtypes: float64(3), object(7)
memory usage: 3.1+ MB

str

In [24]:
df.Restaurant_id.duplicated().sum()
df.URL_TA.duplicated().sum()

20

In [11]:
display(df[df.Restaurant_id.duplicated()].head())

,Restaurant_id,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
174,id_2044,Budapest,['Italian'],2045.0,3.5,NaN,5.0,"[[], []]",/Restaurant_Review-g274887-d10498197-Reviews-P...,d10498197
193,id_8,Ljubljana,"['European', 'Central European', 'Vegetarian F...",9.0,4.5,$$ - $$$,816.0,"[['Casual chic restaurant!', 'Good but a littl...",/Restaurant_Review-g274873-d8124300-Reviews-Ro...,d8124300
201,id_72,Brussels,"['Belgian', 'European', 'International', 'Vege...",73.0,4.0,$$ - $$$,779.0,"[['Delicious', 'They dealt with the problems v...",/Restaurant_Review-g188644-d4014123-Reviews-Ab...,d4014123
216,id_2273,Vienna,NaN,2275.0,4.5,NaN,2.0,"[[], []]",/Restaurant_Review-g190454-d11903856-Reviews-G...,d11903856
271,id_773,Vienna,"['Austrian', 'European', 'Central European', '...",774.0,4.0,$$$$,67.0,"[['Very nice dinner 👌', 'unique style'], ['02/...",/Restaurant_Review-g190454-d5976718-Reviews-Re...,d5976718

In [12]:
display(df[df.Restaurant_id=='id_2044'])

,Restaurant_id,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
140,id_2044,Barcelona,"['Italian', 'Mediterranean']",2045.0,4.5,$$ - $$$,89.0,"[['Real Sicilian cuisine', 'A really nice surp...",/Restaurant_Review-g187497-d8118086-Reviews-Or...,d8118086
174,id_2044,Budapest,['Italian'],2045.0,3.5,NaN,5.0,"[[], []]",/Restaurant_Review-g274887-d10498197-Reviews-P...,d10498197
3030,id_2044,London,"['Asian', 'Thai', 'Vegetarian Friendly', 'Vega...",2048.0,4.5,$$ - $$$,75.0,"[['Hidden up a little alley ....', 'Best ribs'...",/Restaurant_Review-g186338-d11838055-Reviews-S...,d11838055
20646,id_2044,Vienna,NaN,2046.0,4.5,NaN,7.0,"[['Bio taste', 'Perfect to begin the day!'], [...",/Restaurant_Review-g190454-d8811567-Reviews-Ka...,d8811567
20653,id_2044,Stockholm,NaN,2047.0,3.5,NaN,2.0,"[['OK coffee', 'A lucky find of great coffee']...",/Restaurant_Review-g189852-d9702108-Reviews-Ol...,d9702108
23141,id_2044,Warsaw,NaN,2046.0,3.0,NaN,5.0,"[['Beef in Thai'], ['04/04/2017']]",/Restaurant_Review-g274856-d10046967-Reviews-C...,d10046967
31384,id_2044,Lisbon,NaN,2047.0,5.0,NaN,NaN,"[[], []]",/Restaurant_Review-g189158-d13298844-Reviews-M...,d13298844
32334,id_2044,Paris,['Vegetarian Friendly'],2045.0,4.5,$$ - $$$,118.0,"[['A very nice place for a brunch', 'Really go...",/Restaurant_Review-g187147-d8439753-Reviews-Le...,d8439753

In [20]:
for r in df.URL_TA[df.Restaurant_id=='id_2044']:
    print(r)

/Restaurant_Review-g187497-d8118086-Reviews-Origano_cucina_siciliana-Barcelona_Catalonia.html
/Restaurant_Review-g274887-d10498197-Reviews-Pizza_Escobar-Budapest_Central_Hungary.html
/Restaurant_Review-g186338-d11838055-Reviews-Siam_Secret-London_England.html
/Restaurant_Review-g190454-d8811567-Reviews-Kaas_Am_Markt-Vienna.html
/Restaurant_Review-g189852-d9702108-Reviews-Olas_Kaffebar-Stockholm.html
/Restaurant_Review-g274856-d10046967-Reviews-Chinski_Ryz-Warsaw_Mazovia_Province_Central_Poland.html
/Restaurant_Review-g189158-d13298844-Reviews-Mediterraneo-Lisbon_Lisbon_District_Central_Portugal.html
/Restaurant_Review-g187147-d8439753-Reviews-Le_SweetSpot-Paris_Ile_de_France.html

In [35]:
from selenium.webdriver.firefox.options import Options

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

chrome_options = Options()
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--headless')
chrome_options.add_argument('--disable-extensions')
chrome_options.add_argument("--disable-dev-shm-usage");
driver = webdriver.Firefox(options=chrome_options)

In [57]:
from os import listdir
from os.path import isfile, join
onlyfiles = [f for f in listdir('.') if isfile(join('.', f))]
onlyfiles = [x for x in onlyfiles if 'restr' in x]
n_str_list = [x.split('ts')[1].split('.')[0] for x in onlyfiles]
n_str_list.remove('')
n_str_list.remove('_001')
num = np.max(([int(x) for x in n_str_list if x!='']))
num

ValueError: invalid literal for int() with base 10: '_002'

In [53]:
import re
import json

restraunts = pd.DataFrame()
prev_rest = None
for f in onlyfiles:
    if prev_rest is None:
        prev_rest = pd.read_csv(f,sep=';')
    else:
        temp_restr = pd.read_csv(f,sep=';')
        prev_rest = prev_rest.append(temp_restr,ignore_index=True)

file_n = num
for i, r in df[~df['ID_TA'].isin(prev_rest['ID_TA'])].iterrows():
    file_n+=1
    if file_n%100 ==0:
        restraunts.to_csv('restraunts'+str(file_n) + '.csv',sep=';',index=False)
        restraunts = pd.DataFrame()
    if i%10 == 0:
        print(i)
    #try:
    driver.get('https://www.tripadvisor.com'+r['URL_TA'])
    html = driver.page_source
    soup = BeautifulSoup(html)
    
    over_rank = soup.find('a',{'class':'fhGHT'})
    rank=None
    if over_rank:
        over_rank = over_rank.span.text.replace(',','').split(" of ")
        rank = re.search(r'(\d+)',over_rank[0])
        if len(over_rank)>1:
            over_rank = re.search(r'(\d+)',over_rank[1])
    if rank:
        rank = int(rank.group(0))
    try:
        if over_rank and type(over_rank)!='<class \'list\'>' or '<class \'str\'>':
            over_rank = int(over_rank.group(0))
    except:
        over_rank=None
    reviews_cnt = soup.find('span',{'class':'eBTWs'})
    if reviews_cnt:
        reviews_cnt = int(reviews_cnt.text.split(' ')[0].replace(',',''))
    
    price_cuisines = soup.find_all('a', {'class':'drUyy'})
    cuisines=set()
    price = None
    if price_cuisines:
        for it in price_cuisines:
            if re.search(r'\$',it.text):
                price = it.text.strip()
            else:
                cuisines.add(it.text.strip())
    specials = soup.find_all(attrs={'class':'cfvAV'})
    specials_headers = soup.find_all(attrs={'class':'dMshX b'})
    price_max = None
    price_min = None
    price_range = None
    diets=[]
    if specials_headers:
        for i, val in enumerate(specials_headers):
            if val.text == "PRICE RANGE":
                price_range = specials[i].text.replace('RUB','').replace(',','')
            elif val.text == "CUISINES":
                cus_tmp = []
                c_t = specials[i].text.split(',')
                for c in c_t:
                    cus_tmp.append(c.strip())
            elif val.text == "Special Diets":
                diets=[]
                diets_tmp = specials[i].text.split(',')
                for d in diets_tmp:
                    diets.append(d.strip())
    if cus_tmp:
        cuisines.update(cus_tmp)
    if diets:
        cuisines.update(diets) 
    if price_range:
        tmp = price_range.split('-')
        if len(tmp)>1:
            price_min=int(tmp[0])
            price_max=int(tmp[1])
            price_range=price_max-price_min

    scripts = soup.find_all('script')
    for s in scripts:
        if s.find(text=re.compile("window.__WEB_CONTEXT__=")):
            to_parse = s
            break
    parse_hours = re.search(r'"week_ranges":.*"timezone"',str(to_parse))
    time_break = 0
    if parse_hours:
        hours = []
        for day in json.loads('{'+parse_hours.group(0)+r':0}')['week_ranges']:
            h_cnt = 0
            if not time_break:
                if len(day)>1:
                    time_break=1
            for h in day:
                h_cnt+=(h['close_time']-h['open_time'])/60
            hours.append(h_cnt)
    else:
        hours = None
    if hours:
        work_day_in_week = len(hours)
        hours = np.mean(hours)
    else:
        work_day_in_week = None
    
    location = re.search(r'"latitude":(\d*\.\d*),"longitude":(\d*\.\d*),', str(to_parse))
    if location:
        latitude = float(location.group(1))
        longitude = float(location.group(2))
    else:
        latitude = None
        longitude = None
    
    new_row = {
        'ID_TA':r['ID_TA'],
        'cuisines':cuisines,
        'price':price,
        'price_min':price_min,
        'price_max':price_max,
        'price_range':price_range,
        'work_hours':hours,
        'time_break':time_break,
        'work_day_in_week':work_day_in_week,
        'latitude':latitude,
        'longitude':longitude,
        'rank':rank,
        'over_rank':over_rank,
        'reviews_cnt':reviews_cnt,
        
    }
    restraunts = restraunts.append(new_row,ignore_index=True)
    #except Exception as e:
    #    pprint(e)
         
restraunts

0
10
20
30
40
50
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000
1010
1020
1030
1040
1050
1060
1070
1080
1090
1100
1110
1120
1130
1140
1150
1160
1170
1180
1190
1200
1210
1220
1230
1240
1250
1260
1270
1280
1290
1300
1310
1320
1330
1340
1350
1360
1370
1380
1390
1400
1410
1420
1430
1440
1450
1460
1470
1480
1490
1500
1510
1520
1530
1540
1550
1560
1570
1580
1590
1600
1610
1620
1630
1640
1650
1660
1670
1680
1690
1700
1710
1720
1730
1740
1750
1770
1780
1790
1800
1810
1820
1830
1840
1850
1860
1870
1880
1890
1900
1920
1930
1940
1950
1960
1970
1980
1990
2000
2010
2020
2030
2040
2050
2060
2070
2080
2090
2100
2110
2120
2130
2140
2150
2160
2170
2180
2190
2210
2220
2230
2240
2260
2270
2280
2290
2300
2310
2320
2330
2340
2350
2360
2370
2380
2390
2400
2410
2420
2430
2440
2450
2460
2470
2480
2490
2500
2510
2520
2530
2540
2550
2560
2570
2580
2590
2600
2610
2620
2630
2640
2650
2660
2670
2680
2690
2700
2710
2720
2730
2740
2750
2760
2770
2780
2790
2800
2810
2820
2830
2840
2850
2860
2870
2880
2890
2900
2910
2920
2930
2940
2950
2960
2970
2980
2990
3000
3010
3020
3030
3040
3050
3060
3070
3080
3090
3100
3110
3120
3130
3140
3150
3160
3170
3180
3190
3200
3210
3220
3230
3240
3250
3260
3270
3280
3290
3300
3310
3320
3330
3340
3350
3360
3370
3380
3390
3400
3410
3420
3430
3440
3450
3460
3470
3480
3490
3500
3510
3520
3530
3540
3550
3560
3570
3580
3590
3600
3610
3620
3630
3640
3650
3660
3670
3680
3690
3700
3710
3720
3730
3740
3750
3760
3770
3780
3790
3800
3810
3820
3830
3840
3850
3860
3870
3880
3890
3900
3910
3920
3930
3940
3950
3960
3970
3980
3990
4000
4010
4020
4030
4040
4050
4060
4070
4080
4090
4100
4110
4120
4130
4140
4150
4160
4170
4180
4190
4200
4210
4230
4240
4250
4260
4270
4280
4290
4300
4310
4320
4330
4340
4350
4360
4370
4380
4390
4410
4420
4430
4440
4450
4460
4470
4480
4490
4500
4510
4520
4530
4540
4550
4570
4580
4590
4600
4610
4620
4630
4640
4650
4660
4670
4680
4690
4700
4710
4720
4730
4740
4750
4760
4770
4780
4790
4800
4810
4820
4830
4840
4850
4860
4870
4880
4890
4900
4910
4920
4930
4940
4950
4960
4970
4980
4990
5000
5010
5020
5030
5050
5060
5070
5080
5090
5100
5110
5120
5130
5140
5150
5160
5180
5190
5200
5210
5220
5230
5240
5250
5260
5270
5280
5290
5300
5310
5320
5330
5340
5350
5360
5370
5380
5390
5400
5410
5420
5430
5440
5450
5460
5470
5480
5490
5500
5510
5520
5530
5540
5550
5560
5570
5580
5590
5600
5610
5620
5630
5640
5650
5660
5670
5680
5690
5700
5710
5720
5730
5740
5750
5760
5770
5780
5790
5800
5810
5820
5830
5840
5850
5860
5870
5880
5890
5900
5910
5920
5930
5940
5950
5960
5970
5980
5990
6000
6010
6020
6030
6040
6050
6060
6070
6080
6100
6110
6120
6130
6140
6150
6160
6170
6180
6190
6200
6210
6220
6230
6240
6250
6260
6270
6280
6290
6300
6310
6320
6330
6340
6350
6360
6370
6380
6390
6400
6410
6420
6440
6450
6460
6470
6480
6490
6500
6510
6520
6530
6540
6550
6560
6570
6580
6590
6600
6610
6620
6640
6650
6660
6670
6680
6690
6700
6710
6720
6730
6740
6750
6760
6770
6780
6790
6800
6810
6820
6830
6840
6850
6860
6870
6890
6900
6910
6920
6930
6940
6950
6960
6970
6980
6990
7000
7010
7020
7030
7040
7050
7060
7070
7080
7090
7100
7110
7120
7130
7140
7150
7160
7170
7180
7190
7200
7210
7220
7230
7240
7250
7260
7270
7280
7290
7300
7310
7320
7330
7340
7350
7360
7370
7380
7390
7400
7410
7430
7440
7450
7460
7470
7480
7490
7500
7510
7520
7530
7540
7550
7560
7570
7580
7590
7600
7610
7620
7630
7640
7650
7660
7670
7680
7690
7700
7710
7720
7730
7740
7750
7760
7770
7780
7790
7800
7810
7820
7830
7840
7850
7860
7870
7880
7890
7900
7910
7920
7930
7940
7950
7960
7970
7980
7990
8000
8010
8020
8030
8040
8050
8060
8070
8080
8090
8100
8110
8120
8130
8140
8150
8160
8170
8180
8190
8200
8210
8220
8230
8240
8250
8260
8270
8280
8290
8300
8310
8320
8330
8340
8350
8360
8370
8380
8390
8400
8410
8420
8430
8440
8450
8460
8470
8480
8490
8500
8510
8520
8530
8540
8550
8560
8570
8580
8590
8600
8610
8620
8630
8640
8650
8660
8670
8680
8690
8700
8710
8720
8730
8740
8750
8760
8770
8780
8790
8800
8810
8820
8830
8840
8850
8860
8870
8880
8890
8900
8910
8920
8930
8940
8950
8960
8970
8980
8990
9000
9010
9020
9030
9040
9050
9060
9070
9080
9090
9100
9110
9120
9130
9140
9150
9160
9170
9180
9190
9200
9210
9220
9230
9240
9250
9260
9270
9280
9290
9300
9310
9320
9330
9340
9350
9360
9370
9380
9390
9400
9410
9420
9430
9440
9450
9460
9470
9480
9490
9500
9510
9520
9530
9540
9550
9560
9570
9580
9590
9600
9610
9620
9630
9640
9650
9660
9670
9680
9690
9700
9710
9730
9740
9750
9760
9780
9790
9800
9810
9820
9830
9840
9850
9860
9870
9880
9890
9910
9920
9930
9940
9950
9960
9970
9980
10000
10010
10020
10030
10050
10070
10080
10090
10100
10110
10120
10130
10140
10150
10160
10170
10180
10190
10200
10210
10220
10230
10240
10250
10260
10270
10280
10290
10300
10310
10320
10330
10340
10350
10360
10370
10380
10390
10400
10410
10420
10430
10440
10450
10460
10470
10480
10490
10500
10510
10520
10530
10540
10550
10560
10570
10580
10590
10600
10610
10620
10630
10640
10650
10660
10670
10680
10690
10700
10710
10720
10730
10740
10750
10760
10770
10780
10790
10800
10810
10820
10840
10850
10860
10870
10880
10890
10900
10910
10920
10930
10940
10950
10960
10970
10980
10990
11000
11010
11020
11030
11040
11050
11060
11070
11080
11090
11100
11130
11140
11150
11160
11170
11180
11190
11200
11210
11220
11230
11240
11250
11260
11270
11280
11290
11300
11310
11320
11330
11340
11350
11360
11370
11380
11390
11400
11410
11420
11430
11440
11450
11460
11470
11480
11490
11500
11510
11520
11530
11540
11550
11560
11570
11580
11590
11600
11610
11620
11630
11640
11650
11660
11670
11680
11690
11700
11710
11720
11730
11740
11750
11760
11770
11780
11790
11800
11810
11820
11830
11840
11850
11860
11870
11880
11890
11900
11910
11920
11940
11950
11960
11970
11980
11990
12000
12010
12020
12030
12040
12050
12060
12080
12090
12100
12110
12130
12140
12150
12160
12170
12180
12190
12200
12210
12220
12230
12240
12250
12260
12270
12280
12290
12300
12310
12320
12340
12350
12360
12370
12380
12390
12400
12410
12420
12430
12440
12450
12460
12470
12480
12490
12500
12510
12520
12530
12540
12550
12560
12570
12580
12590
12600
12610
12620
12630
12640
12650
12660
12670
12680
12690
12700
12710
12720
12730
12740
12750
12760
12770
12780
12790
12800
12810
12820
12830
12840
12850
12860
12870
12880
12890
12900
12910
12920
12930
12940
12950
12960
12970
12990
13000
13010
13020
13030
13040
13050
13060
13070
13080
13090
13100
13110
13120
13130
13140
13150
13160
13170
13180
13190
13200
13210
13220
13230
13240
13250
13260
13270
13280
13290
13300
13310
13320
13330
13340
13350
13360
13370
13380
13390
13400
13410
13420
13440
13450
13460
13470
13480
13490
13500
13510
13520
13530
13540
13550
13560
13570
13580
13600
13610
13630
13640
13650
13660
13670
13680
13690
13700
13710
13720
13730
13740
13750
13760
13770
13780
13790
13800
13810
13820
13830
13840
13850
13860
13870
13880
13890
13900
13910
13920
13930
13940
13950
13960
13970
13980
13990
14000
14010
14020
14030
14040
14050
14060
14070
14080
14090
14100
14110
14120
14130
14140
14150
14160
14170
14180
14190
14200
14210
14220
14230
14240
14250
14260
14270
14280
14290
14300
14310
14320
14330
14340
14350
14360
14370
14380
14390
14400
14410
14420
14430
14440
14450
14460
14470
14480
14490
14500
14510
14520
14530
14540
14550
14560
14570
14580
14590
14600
14610
14620
14630
14640
14650
14660
14670
14680
14690
14700
14710
14720
14730
14740
14750
14760
14770
14780
14790
14800
14810
14830
14840
14850
14860
14870
14880
14890
14900
14910
14920
14930
14940
14950
14960
14970
14980
14990
15000
15010
15020
15030
15040
15060
15070
15080
15090
15100
15110
15120
15130
15140
15150
15160
15180
15190
15200
15210
15220
15230
15240
15250
15260
15270
15280
15290
15300
15310
15320
15330
15340
15350
15360
15370
15380
15390
15400
15410
15420
15430
15440
15450
15460
15470
15480
15490
15500
15510
15520
15530
15540
15550
15560
15570
15580
15590
15600
15610
15620
15630
15640
15650
15660
15670
15680
15690
15700
15710
15720
15730
15740
15750
15760
15770
15780
15790
15800
15810
15820
15830
15840
15850
15860
15870
15880
15890
15900
15910
15920
15930
15940
15950
15960
15970
15980
15990
16010
16020
16030
16040
16050
16060
16070
16080
16090
16100
16110
16120
16130
16140
16150
16160
16170
16180
16190
16200
16210
16220
16230
16240
16250
16260
16270
16280
16290
16300
16310
16320
16330
16340
16350
16360
16370
16380
16390
16400
16410
16420
16430
16440
16450
16460
16470
16480
16490
16500
16510
16520
16530
16540
16550
16560
16570
16580
16590
16600
16610
16620
16630
16640
16650
16660
16670
16680
16690
16700
16710
16720
16730
16740
16750
16760
16770
16780
16790
16800
16810
16820
16830
16840
16850
16860
16870
16880
16890
16900
16910
16920
16930
16940
16950
16960
16970
16980
16990
17000
17010
17020
17030
17040
17050
17060
17070
17080
17090
17110
17120
17130
17140
17150
17160
17170
17180
17190
17200
17210
17220
17230
17240
17250
17260
17270
17280
17290
17300
17310
17320
17330
17340
17350
17360
17370
17380
17390
17400
17410
17420
17440
17450
17460
17470
17480
17490
17500
17510
17530
17540
17550
17560
17570
17580
17590
17600
17610
17620
17630
17640
17650
17660
17670
17680
17690
17700
17710
17720
17730
17740
17750
17760
17770
17780
17790
17800
17810
17820
17830
17840
17850
17860
17870
17880
17890
17900
17910
17920
17930
17940
17960
17970
17980
17990
18000
18010
18020
18030
18040
18050
18060
18070
18080
18090
18100
18110
18120
18130
18140
18150
18160
18180
18190
18200
18210
18220
18230
18240
18250
18260
18270
18280
18290
18300
18310
18320
18330
18340
18350
18360
18370
18380
18390
18400
18410
18420
18430
18440
18450
18460
18470
18480
18490
18500
18510
18520
18530
18540
18550
18560
18570
18580
18600
18610
18620
18630
18640
18650
18660
18670
18680
18690
18700
18710
18720
18730
18740
18750
18760
18770
18780
18790
18800
18810
18820
18830
18840
18850
18860
18870
18880
18890
18900
18910
18920
18930
18940
18950
18960
18970
18980
18990
19000
19010
19020
19030
19040
19050
19060
19070
19080
19090
19110
19120
19130
19140
19150
19160
19180
19190
19200
19210
19220
19230
19240
19250
19260
19270
19280
19290
19300
19310
19320
19330
19340
19350
19360
19370
19380
19390
19400
19410
19420
19430
19440
19450
19460
19470
19480
19490
19500
19510
19520
19530
19540
19550
19560
19570
19580
19590
19600
19610
19620
19630
19650
19660
19670
19680
19690
19700
19710
19720
19730
19740
19750
19760
19770
19780
19790
19800
19810
19830
19840
19850
19860
19870
19880
19890
19900
19910
19920
19930
19940
19950
19960
19980
19990
20000
20010
20020
20030
20040
20050
20060
20070
20080
20090
20100
20110
20120
20130
20140
20150
20160
20170
20180
20190
20200
20210
20220
20230
20240
20250
20260
20270
20280
20290
20300
20320
20330
20340
20350
20360
20370
20380
20390
20400
20410
20420
20440
20450
20460
20470
20480
20490
20510
20520
20530
20540
20550
20560
20570
20580
20590
20600
20610
20620
20630
20640
20650
20660
20670
20680
20690
20700
20710
20720
20730
20740
20750
20760
20770
20780
20790
20800
20810
20820
20830
20840
20850
20860
20870
20880
20890
20900
20910
20920
20930
20940
20950
20960
20970
20980
20990
21000
21010
21020
21030
21040
21050
21060
21070
21080
21090
21100
21110
21120
21130
21140
21150
21160
21170
21190
21200
21220
21230
21240
21250
21260
21270
21280
21290
21300
21310
21320
21330
21340
21350
21360
21380
21390
21400
21410
21420
21430
21440
21450
21460
21470
21480
21490
21500
21510
21520
21530
21540
21550
21560
21570
21580
21590
21600
21610
21620

,ID_TA,cuisines,price,price_min,price_max,price_range,work_hours,time_break,work_day_in_week,latitude,longitude,rank,over_rank,reviews_cnt
0,d8570887,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
1,d2188159,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
2,d6979947,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
3,d2720510,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
4,d7123275,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,d11999956,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
95,d8753348,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
96,d7337366,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
97,d793170,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
98,d10047799,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None

In [54]:
display(restraunts)
restraunts.to_csv('restraunts_002.csv',sep=';',index=False)

,ID_TA,cuisines,price,price_min,price_max,price_range,work_hours,time_break,work_day_in_week,latitude,longitude,rank,over_rank,reviews_cnt
0,d8570887,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
1,d2188159,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
2,d6979947,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
3,d2720510,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
4,d7123275,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,d11999956,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
95,d8753348,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
96,d7337366,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
97,d793170,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None
98,d10047799,"{Gastropub, Italian}",None,None,None,None,None,0.0,None,None,None,None,None,None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21088 entries, 0 to 21087
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID_TA             21088 non-null  object
 1   cuisines          21088 non-null  object
 2   price             15167 non-null  object
 3   price_min         5634 non-null   object
 4   price_max         5634 non-null   object
 5   price_range       5634 non-null   object
 6   work_hours        12257 non-null  object
 7   time_break        21088 non-null  float64
 8   work_day_in_week  12257 non-null  object
 9   latitude          12636 non-null  object
 10  longitude         12636 non-null  object
 11  rank              17938 non-null  object
 12  over_rank         17938 non-null  object
 13  reviews_cnt       17938 non-null  object
dtypes: float64(1), object(13)
memory usage: 2.3+ MB

In [58]:
restraunts=pd.read_csv('restraunts.csv',sep=';')

for f in onlyfiles:
    if f != 'restraunts.csv':
        temp_restr = pd.read_csv(f,sep=';')
        restraunts = restraunts.append(temp_restr,ignore_index=True)

In [59]:
display(restraunts)

,ID_TA,cuisines,price,price_min,price_max,price_range,work_hours,time_break,work_day_in_week,latitude,longitude,rank,over_rank,reviews_cnt
0,d3842331,"{'Vegetarian Friendly', 'Vegan Options', 'Ital...",$,NaN,NaN,NaN,5.428571,1.0,7.0,45.481716,9.219533,174.0,6806.0,408.0
1,d7823625,"{'French', 'Seafood', 'European'}",$$ - $$$,NaN,NaN,NaN,6.642857,1.0,7.0,48.865635,2.346342,3753.0,15768.0,192.0
2,d1347989,"{'French', 'Seafood', 'European'}",NaN,NaN,NaN,NaN,NaN,0.0,NaN,52.511910,13.240770,5027.0,5679.0,6.0
3,d7620398,"{'Wine Bar', 'Mediterranean', 'Portuguese', 'E...",$$ - $$$,1041.0,2603.0,1562.0,4.500000,0.0,7.0,NaN,NaN,274.0,4626.0,1187.0
4,d5775838,"{'Cafe', 'Mediterranean', 'European'}",$$ - $$$,NaN,NaN,NaN,14.142857,0.0,7.0,NaN,NaN,4021.0,10457.0,137.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40091,d7123578,"{'Fast Food', 'Pizza', 'Italian'}",$,NaN,NaN,NaN,NaN,0.0,NaN,50.086853,14.445791,2303.0,4683.0,10.0
40092,d11917576,"{'Fast Food', 'Pizza', 'Italian'}",$$$$,1970.0,18862.0,16892.0,10.428571,0.0,7.0,50.045204,19.929110,725.0,1538.0,10.0
40093,d2705390,"{'Cafe', 'Italian'}",NaN,513.0,1025.0,512.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
40094,d7144184,"{'Cafe', 'Italian'}",$$ - $$$,NaN,NaN,NaN,4.357143,0.0,7.0,48.857113,2.353745,5403.0,15768.0,229.0
40095,d991628,"{'Cafe', 'Italian'}",NaN,NaN,NaN,NaN,7.714286,0.0,7.0,NaN,NaN,8671.0,10457.0,1.0

In [30]:
for c in df.columns:
    if df[c].dtype=='object':
        df.drop(c,axis=1,inplace=True)

df.fillna(0,inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Ranking            40000 non-null  float64
 1   Rating             40000 non-null  float64
 2   Number of Reviews  40000 non-null  float64
dtypes: float64(3)
memory usage: 937.6 KB

# Разбиваем датафрейм на части, необходимые для обучения и тестирования модели

In [31]:
# Х - данные с информацией о ресторанах, у - целевая переменная (рейтинги ресторанов)
#X = df.drop(['Restaurant_id', 'Rating'], axis = 1)
X = df.drop(['Rating'], axis = 1)
y = df['Rating']

In [32]:
# Загружаем специальный инструмент для разбивки:
from sklearn.model_selection import train_test_split

In [33]:
# Наборы данных с меткой "train" будут использоваться для обучения модели, "test" - для тестирования.
# Для тестирования мы будем использовать 25% от исходного датасета.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

# Создаём, обучаем и тестируем модель

In [34]:
# Импортируем необходимые библиотеки:
from sklearn.ensemble import RandomForestRegressor # инструмент для создания и обучения модели
from sklearn import metrics # инструменты для оценки точности модели

In [35]:
# Создаём модель
regr = RandomForestRegressor(n_estimators=100)

# Обучаем модель на тестовом наборе данных
regr.fit(X_train, y_train)

# Используем обученную модель для предсказания рейтинга ресторанов в тестовой выборке.
# Предсказанные значения записываем в переменную y_pred
y_pred = regr.predict(X_test)

In [36]:
# Сравниваем предсказанные значения (y_pred) с реальными (y_test), и смотрим насколько они в среднем отличаются
# Метрика называется Mean Absolute Error (MAE) и показывает среднее отклонение предсказанных значений от фактических.
print('MAE:', metrics.mean_absolute_error(y_test, y_pred))

MAE: 0.4310721363997114